### ISSUE TITLE
Nawet nie dziala...

### ISSUE THREAD

**Issue by fenrirx22** [MaciejSzaflik/AI-Experiments#1]
![capture](https://cloud.githubusercontent.com/assets/10367216/5598215/409a9dc0-92b2-11e4-9a88-245779a09cc9.PNG)

?? Wstyd...

Wypełnij readme!

**Comment by MaciejSzaflik** [comment]
W akutalniej wersji proszę o uruchamianie na firefoxie (im nowszy tym lepszy)
